Not Found: /admin/
"GET /admin/ HTTP/1.1" 404 11248
"GET /static/assets/maps/style.css.map HTTP/1.1" 404 1889
"GET /static/assets/maps/style.css.map HTTP/1.1" 404 1889
"GET /static/assets/maps/style.css.map HTTP/1.1" 404 1889
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 11278
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 11278
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 11278
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 11278
Not Found: /hijack/
"GET /hijack/ HTTP/1.1" 404 11626
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 11278
Internal Server Error: /secrete/logout/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: axes_accessattempt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\contrib\admin\sites.py", line 260, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\contrib\admin\sites.py", line 405, in logout
    return LogoutView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\contrib\auth\views.py", line 137, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\contrib\auth\views.py", line 141, in post
    auth_logout(request)
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 170, in logout
    user_logged_out.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\axes\signals.py", line 38, in handle_user_logged_out
    AxesProxyHandler.user_logged_out(*args, **kwargs)
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\axes\helpers.py", line 617, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\axes\handlers\proxy.py", line 133, in user_logged_out
    return cls.get_implementation().user_logged_out(sender, request, user, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\axes\handlers\database.py", line 308, in user_logged_out
    clean_expired_user_attempts(request)
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\axes\attempts.py", line 83, in clean_expired_user_attempts
    count, _ = AccessAttempt.objects.filter(attempt_time__lt=threshold).delete()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\models\query.py", line 1187, in delete
    collector.collect(del_query)
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\models\deletion.py", line 282, in collect
    new_objs = self.add(
               ^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\models\deletion.py", line 124, in add
    if not objs:
           ^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\models\query.py", line 414, in __bool__
    self._fetch_all()
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: axes_accessattempt
"POST /secrete/logout/ HTTP/1.1" 500 267819
Too Many Requests: /secrete/login/
"POST /secrete/login/?next=/secrete/ HTTP/1.1" 429 64
Too Many Requests: /secrete/login/
"POST /secrete/login/?next=/secrete/ HTTP/1.1" 429 64
Too Many Requests: /secrete/login/
"POST /secrete/login/?next=/secrete/ HTTP/1.1" 429 64
Forbidden: /api/electricity-bill/
"POST /api/electricity-bill/ HTTP/1.1" 403 58
Bad Request: /api/bonus-to-bank/
"POST /api/bonus-to-bank/ HTTP/1.1" 400 77
Bad Request: /api/buy-airtime/
"POST /api/buy-airtime/ HTTP/1.1" 400 52
Internal Server Error: /api/jamb-registration/
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\OneDrive\Desktop\5 star projects\VTU WEBSITE\api\views.py", line 1617, in post
    data = request.data.dict()  # Convert QueryDict to regular dict
           ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'dict'
"POST /api/jamb-registration/ HTTP/1.1" 500 21004
